/**
 * Templates preloader.
 * Used by autogenerated script in production mode.
 */
define(['angular'], function(angular) {
  angular.module('templates', []).run(function() {
    console.warn('Templates module stub. Autogenerated.');
  });
})
